In [3]:
import numpy as np
L = np.random.random(100)
sum(L)

np.float64(51.176532697839576)

In [4]:
np.sum(L)

np.float64(51.17653269783958)

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

26.5 ms ± 758 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
106 μs ± 279 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Minimum and Maximum

In [6]:
min(big_array), max(big_array)

(np.float64(2.066686566659648e-06), np.float64(0.9999963884224546))

In [7]:
np.min(big_array), np.max(big_array)

(np.float64(2.066686566659648e-06), np.float64(0.9999963884224546))

In [8]:
%timeit min(big_array)
%timeit np.min(big_array)

18.8 ms ± 546 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
69.2 μs ± 189 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
print(big_array.min(), big_array.max(), big_array.sum())

2.066686566659648e-06 0.9999963884224546 500471.7348012057


Multi dimensional aggregates

In [10]:
M = np.random.random((3, 4))
print(M)

[[0.84153217 0.01753608 0.80025966 0.33543187]
 [0.51603955 0.6585121  0.9489276  0.67634488]
 [0.38817604 0.47807098 0.06433431 0.36875555]]


In [11]:
M.sum()

np.float64(6.093920779461337)

In [12]:
M.min(axis=0)

array([0.38817604, 0.01753608, 0.06433431, 0.33543187])

In [13]:
M.max(axis=1)

array([0.84153217, 0.9489276 , 0.47807098])