In [1]:
import numpy as np

How to add a border (filled with 0's) around an existing array?

In [46]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [34]:
# 0 * np.nan # nan
# np.nan == np.nan # False
# np.inf > np.nan # False
# np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False

False

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
x = np.zeros((8, 8))
# Set 1s on alternating columns starting from index 1 for even rows
x[::2, 1::2] = 1

# Set 1s on alternating columns starting from index 0 for odd rows
x[1::2, ::2] = 1

x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element


In [47]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


Create a checkerboard 8x8 matrix using the tile function

In [48]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5x5 random matrix

In [51]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.93865084 -0.20890663 -0.24088425  0.11215292 -1.18500849]
 [ 0.3183365   1.43380579 -0.8180503  -1.11106188  1.20737576]
 [ 0.87098055 -1.28523225 -1.55708124 -1.32662913  1.40587489]
 [ 1.5754097   0.41052536  1.30341618 -0.39424957 -0.96652161]
 [-0.47999551 -0.07268089  0.01286267  0.27242772  1.66178456]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [53]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [56]:
X = np.ones((5,3)) @ np.ones((3,2))
print(X)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Given a 1D array, negate all elements which are between 3 and 8, in place.

In [57]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


What is the output of the following script?

In [70]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


Consider an integer vector Z, which of these expressions are legal?

In [74]:
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

What are the result of the following expressions?

In [76]:
np.array(0) / np.array(0)

/var/folders/vq/tpq3c_k109bbkmytxbgbcc2r0000gn/T/ipykernel_3297/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [77]:
np.array(0) // np.array(0)

/var/folders/vq/tpq3c_k109bbkmytxbgbcc2r0000gn/T/ipykernel_3297/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [78]:
np.array([np.nan]).astype(int).astype(float)

/var/folders/vq/tpq3c_k109bbkmytxbgbcc2r0000gn/T/ipykernel_3297/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

How to round away from zero a float array ?

In [83]:
x = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(x)), x))

[ 5. -9. -4.  1. -9. -9.  2.  1.  9.  5.]


How to find common values between two arrays?

In [88]:
x1 = np.random.randint(0,10,10)
print(x1)
x2 = np.random.randint(0,10,10)
print(x2)
print(np.intersect1d(x1,x2))

[8 4 3 6 7 2 2 4 2 0]
[0 1 2 0 9 2 9 9 7 4]
[0 2 4 7]
