In [1]:
import numpy as np

How to ignore all numpy warnings (not recommended)?

In [3]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

Is the following expressions true?

In [4]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

/var/folders/vq/tpq3c_k109bbkmytxbgbcc2r0000gn/T/ipykernel_4132/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2026-07-12 2026-07-13 2026-07-14


How to get all the dates corresponding to the month of July 2016?

In [7]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

How to compute ((A+B)*(-A/2)) in place (without copy)?

In [8]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

Extract the integer part of a random array using 5 different methods

In [9]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6. 8. 7. 8. 6. 2. 1. 6. 4. 7.]
[6. 8. 7. 8. 6. 2. 1. 6. 4. 7.]
[6. 8. 7. 8. 6. 2. 1. 6. 4. 7.]
[6 8 7 8 6 2 1 6 4 7]
[6. 8. 7. 8. 6. 2. 1. 6. 4. 7.]


Create a 5x5 matrix with row values ranging from 0 to 4

In [10]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Consider a generator function that generates 10 integers and use it to build an array

In [12]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Create a vector of size 10 with values ranging from 0 to 1, both excluded (

In [13]:
y = np.linspace(0,1,11,endpoint=False)[1:]
print(y)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [17]:
np.random.random(10)

array([0.58235488, 0.671074  , 0.7546827 , 0.65865231, 0.06471009,
       0.25768258, 0.75882882, 0.12934673, 0.68142243, 0.84324967])

Create a random vector of size 10 and sort it

In [16]:
y = np.random.random(10)
y.sort()
print(y)

[0.06712938 0.07443663 0.12689384 0.2505875  0.2881097  0.57307658
 0.60806166 0.6817562  0.88823749 0.95941103]


How to sum a small array faster than np.sum?

In [19]:
x = np.arange(10)
np.add.reduce(x)

[0 1 2 3 4 5 6 7 8 9]


np.int64(45)

Consider two random array A and B, check if they are equal

In [20]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


Make an array immutable (read-only)

In [22]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [24]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.23762915 0.51856957 1.01199715 1.0114365  0.94223362 0.59500067
 0.70838008 0.16802154 0.5800162  1.09211009]
[0.68165005 1.2002851  0.56438392 0.51811454 1.36486079 1.27691187
 0.97141551 1.36073627 1.01704365 1.10981215]


Create random vector of size 10 and replace the maximum value by 0

In [25]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.66090894 0.53093569 0.         0.75035671 0.48801757 0.51904785
 0.33717807 0.89586323 0.3281605  0.02380701]
