In [1]:
import numpy as np
np.__version__

'2.5.0'

In [2]:
# NumPy Array Attributes
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Each array has attributes
ndim (the number of dimensions),
shape (the size of each dimension), and
size (the total size of the array):

In [4]:
# The data type of the array
print("dtype:", x3.dtype)

dtype: int64


In [7]:
# itemsize, which lists the size (in bytes) of each array element,
print("itemsize:", x3.itemsize, "bytes")
print("Size:", x3.size, "bytes")
# nbytes, which lists the total size (in bytes) of the array
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
Size: 60 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[-1]

np.int64(9)

In [11]:
x1[-2]

np.int64(7)

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 0]

np.int64(3)

In [16]:
x2[2, -1]

np.int64(7)

In [17]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [18]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

Array Slicing: Accessing Subarrays

In [20]:
# x[start:stop:step]
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [22]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [23]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [33]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [27]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [28]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

Multi-dimensional subarrays

In [30]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [32]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [34]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Accessing array rows and columns

In [35]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [36]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [37]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


Subarrays as no-copy views

In [39]:
print (x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [40]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [41]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [42]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Creating copies of arrays

In [44]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [45]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [46]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Reshaping of Arrays

In [47]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [51]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [52]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

Array Concatenation and Splitting

In [53]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [54]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [56]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [62]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])
# Similary, np.dstack will stack arrays along the third axis.

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting of arrays

In [63]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [64]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [66]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
