In [4]:
import numpy as np
np.__version__

'2.5.0'

In [5]:
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.5",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name"

In [6]:
# Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# itemsize, which lists the size (in bytes) of each array element,
x = np.zeros(10)
print("itemsize:", x.itemsize, "bytes")
print("Size:", x.size, "bytes")
# nbytes, which lists the total size (in bytes) of the array
print("nbytes:", x.nbytes, "bytes")

itemsize: 8 bytes
Size: 10 bytes
nbytes: 80 bytes


In [9]:
# Create a null vector of size 10 but the fifth value which is 1
x[4] = 5
print(x)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49
y = np.arange(10, 50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# Reverse a vector (first element becomes last)
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [16]:
# Create a 3x3 matrix with values ranging from 0 to 8
grid = np.arange(0, 9).reshape((3, 3))
print(grid)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [21]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create a 3x3x3 array with random values
np.random.randint(0, 10, (3, 3))

array([[2, 2, 9],
       [6, 6, 8],
       [4, 3, 9]])

In [26]:
np.random.random((3, 3, 3))

array([[[0.37610307, 0.58617295, 0.78791612],
        [0.11249743, 0.97068036, 0.98400783],
        [0.26650482, 0.79891889, 0.67218102]],

       [[0.81126151, 0.87588286, 0.19278742],
        [0.26919056, 0.64546128, 0.56050685],
        [0.23589008, 0.38271362, 0.10252447]],

       [[0.21392625, 0.88784623, 0.04292024],
        [0.47809512, 0.9617944 , 0.09147157],
        [0.50224502, 0.64635306, 0.77241199]]])

In [29]:
# Create a 10x10 array with random values and find the minimum and maximum values
grid = np.random.random((10, 10))
min = grid.min()
max = grid.max()
print(min, max)

0.009400883314557462 0.9982459069786807


In [31]:
# Create a random vector of size 30 and find the mean value
np.random.random(30).mean()

np.float64(0.460097345971045)

In [32]:
# 1. Create a 2D array filled entirely with 1s
arr = np.ones((5, 5), dtype=int)

# 2. Slice the inner elements and set them to 0
arr[1:-1, 1:-1] = 0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
