In [2]:
from email.mime import image

import numpy as np
from pygments.formatters import img

How to tell if a given 2D array has null columns?

In [3]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


Find the nearest value from a given value in an array

In [4]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48762268583044144


Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [8]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B, '\n')
# Create the iterator with a placeholder for the output
it = np.nditer([A, B, None])

# Iterate and assign the sum to the output operand
for x, y, z in it:
    z[...] = x + y

# Retrieve the final broadcasted sum matrix
result = it.operands[2]
print(result)

[[0]
 [1]
 [2]]
[[0 1 2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


Create an array class that has a name attribute

In [9]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [13]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[2. 2. 2. 7. 4. 3. 3. 2. 1. 4.]
[ 3.  3.  3. 13.  7.  5.  5.  3.  1.  7.]


How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [14]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [27]:
w,h = 8,8
pixels = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
unique_colors = np.unique(pixels, axis=0)
num_colors = len(unique_colors)
num_colors

8

Considering a four dimensions array, how to get sum over the last two axis at once? (

In [28]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 49 54 60]
 [59 45 71 40]
 [54 55 61 68]]
[[49 49 54 60]
 [59 45 71 40]
 [54 55 61 68]]


Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [29]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.54429851 0.59890469 0.48531087 0.60114959 0.31914961 0.47565035
 0.65667165 0.50456701 0.44087801 0.31233342]
0    0.544299
1    0.598905
2    0.485311
3    0.601150
4    0.319150
5    0.475650
6    0.656672
7    0.504567
8    0.440878
9    0.312333
dtype: float64


How to get the diagonal of a dot product?

In [30]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.35625218, 1.28453034, 0.47156139, 1.25124407, 1.28400099])

Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [32]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [34]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


How to swap two rows of an array?

In [35]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [36]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 29) ( 0, 71) ( 5, 20) ( 5, 24) ( 5, 27) ( 5, 30) (10, 17) (10, 65)
 (13, 19) (13, 60) (14, 56) (14, 84) (15, 56) (15, 67) (16, 52) (16, 54)
 (16, 59) (16, 62) (17, 65) (19, 60) (20, 27) (21, 36) (21, 60) (24, 30)
 (29, 71) (36, 60) (52, 62) (54, 59) (56, 67) (56, 84)]


How to get the diagonal of a dot product?

In [3]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.01281102, 0.73982376, 0.84469098, 1.48348391, 1.00605941])

Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [4]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [5]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


How to swap two rows of an array?

In [6]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [8]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 65) ( 4, 68) ( 4, 80) ( 4, 92) ( 5, 33) ( 5, 73) (12, 29) (12, 50)
 (13, 25) (13, 57) (15, 49) (15, 87) (22, 74) (22, 95) (25, 57) (29, 50)
 (33, 73) (40, 58) (40, 92) (49, 87) (58, 92) (65, 68) (65, 77) (65, 85)
 (74, 91) (74, 95) (74, 97) (77, 85) (80, 92) (91, 97)]


Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [9]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


How to compute averages using a sliding window over an array?

In [11]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [12]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


How to negate a boolean, or to change the sign of a float inplace?

In [14]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.70706192, -0.67103279, -0.13787109,  0.64997638,  0.64652034,
        0.16956391,  0.28220565, -0.4472085 , -0.70932865, -0.47468404,
       -0.83669094,  0.1528407 , -0.38617207, -0.34771419, -0.29077417,
       -0.16376524,  0.94384752, -0.88529727,  0.89574408, -0.92403143,
       -0.67641702,  0.96598638, -0.97508812,  0.49079353, -0.72773954,
       -0.0191269 ,  0.98172909, -0.87034015, -0.22130285, -0.51639415,
       -0.1623763 , -0.53779039, -0.49622908, -0.15959665,  0.50830636,
        0.64012792, -0.60918243, -0.86306963, -0.24690829,  0.91011635,
       -0.04280481, -0.26683905,  0.35480494,  0.69337254,  0.18155084,
       -0.68331782,  0.55040564, -0.17752104, -0.27943943, -0.77643058,
       -0.57043689, -0.80745152, -0.76235326,  0.61873198, -0.54548821,
        0.62742321,  0.3180249 ,  0.80441781,  0.3897372 , -0.93987089,
       -0.93467912, -0.38804302, -0.34884198, -0.99116678,  0.22702257,
        0.03863777, -0.51070111,  0.06729865, -0.35370623,  0.18

Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [16]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[6.37547524 1.32618939 3.53265802 3.85886242 8.76846479 5.97500187
 0.74183332 1.1276002  2.19326096 9.73798105]


Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [17]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.24607958  7.64187468 11.06133274 12.22174188  5.80116742  0.64859209
  16.43181686  6.36417631  1.48209002  9.19620274]
 [ 6.70031897 11.68488056  5.30008733  5.28932755 11.71203381 16.29974658
   9.72145378  7.73785732 16.1539177   9.46218389]
 [13.94308456  3.28247878  7.64549801  4.42356393 10.83713601 17.27915329
   2.28752091 13.64552146 14.69522178  5.08161573]
 [10.2076143   7.04692007  1.89815772  2.23666391  4.17473596 11.10698502
   1.59607076  9.27781477  7.89900071  7.37377998]
 [ 2.56623054  3.35351738  2.70638404  4.65924555  1.75856015  7.41349826
   8.49103789  2.42500416  5.89459846  3.37343518]
 [ 6.82003329  2.3861219   0.12334399  3.27965657  3.13461315  9.49429676
   2.89974081  6.24558337  7.04332184  2.56662017]
 [ 0.19971276  3.72446441  5.71405135  7.63631214  1.21822182  4.40186279
  10.5162613   0.44582476  2.93834046  4.36954472]
 [ 7.77036825 10.63216898  6.10439236  5.87839625 12.30044744 17.01617383
   8.50234224  8.74391121 16.69995803  8.30147699]


Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [20]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
#R[r] = Z[z]
print(Z, z)
print(R, r)

[[0 8 6 6 1 3 6 9 7 9]
 [7 0 6 0 1 3 5 2 5 0]
 [9 2 4 3 5 4 1 2 3 5]
 [7 6 6 0 6 4 6 2 8 6]
 [2 7 6 5 6 9 3 5 3 7]
 [3 2 9 2 2 6 4 5 2 5]
 [5 8 7 2 0 3 6 9 1 6]
 [3 2 6 3 8 1 1 1 1 3]
 [5 3 4 1 7 8 5 9 8 6]
 [2 5 3 7 1 1 6 8 2 8]] [slice(0, 4, None), slice(0, 4, None)]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] [slice(1, 5, None), slice(1, 5, None)]


Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [21]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


Compute a matrix rank

In [22]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


How to find the most frequent value in an array?

In [23]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [25]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 0]
   [2 3 3]
   [0 2 4]]

  [[2 0 0]
   [3 3 4]
   [2 4 0]]

  [[0 0 2]
   [3 4 0]
   [4 0 0]]

  [[0 2 3]
   [4 0 3]
   [0 0 2]]

  [[2 3 0]
   [0 3 0]
   [0 2 0]]

  [[3 0 1]
   [3 0 0]
   [2 0 3]]

  [[0 1 2]
   [0 0 4]
   [0 3 1]]

  [[1 2 1]
   [0 4 0]
   [3 1 0]]]


 [[[2 3 3]
   [0 2 4]
   [2 3 3]]

  [[3 3 4]
   [2 4 0]
   [3 3 3]]

  [[3 4 0]
   [4 0 0]
   [3 3 4]]

  [[4 0 3]
   [0 0 2]
   [3 4 1]]

  [[0 3 0]
   [0 2 0]
   [4 1 1]]

  [[3 0 0]
   [2 0 3]
   [1 1 4]]

  [[0 0 4]
   [0 3 1]
   [1 4 0]]

  [[0 4 0]
   [3 1 0]
   [4 0 1]]]


 [[[0 2 4]
   [2 3 3]
   [3 4 0]]

  [[2 4 0]
   [3 3 3]
   [4 0 4]]

  [[4 0 0]
   [3 3 4]
   [0 4 3]]

  [[0 0 2]
   [3 4 1]
   [4 3 3]]

  [[0 2 0]
   [4 1 1]
   [3 3 1]]

  [[2 0 3]
   [1 1 4]
   [3 1 4]]

  [[0 3 1]
   [1 4 0]
   [1 4 2]]

  [[3 1 0]
   [4 0 1]
   [4 2 4]]]


 [[[2 3 3]
   [3 4 0]
   [4 2 2]]

  [[3 3 3]
   [4 0 4]
   [2 2 4]]

  [[3 3 4]
   [0 4 3]
   [2 4 2]]

  [[3 4 1]
   [4 3 3]
   [4 2 0]]

  [[4 1 1]
   

Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [27]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 10  6  8 11]
 [10  9  7  5  3]
 [ 6  7  4 42  9]
 [ 8  5 42  1  5]
 [11  3  9  5  1]]


Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [28]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [29]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


How to implement the Game of Life using numpy arrays?

In [31]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


How to get the n largest values of an array

In [32]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9997 9995 9999 9998]


Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [33]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


How to create a record array from a regular array?

In [34]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


/var/folders/vq/tpq3c_k109bbkmytxbgbcc2r0000gn/T/ipykernel_5909/3979488781.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [35]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


TypeError: 'float' object cannot be interpreted as an integer

Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [36]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[]


Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (

In [37]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 4 2]
 [1 1 4]
 [1 1 4]
 [0 4 3]
 [3 3 4]
 [0 0 2]
 [4 4 4]
 [1 3 0]
 [2 1 0]
 [2 0 1]]
[[1 4 2]
 [1 1 4]
 [1 1 4]
 [0 4 3]
 [3 3 4]
 [0 0 2]
 [1 3 0]
 [2 1 0]
 [2 0 1]]
[[1 4 2]
 [1 1 4]
 [1 1 4]
 [0 4 3]
 [3 3 4]
 [0 0 2]
 [1 3 0]
 [2 1 0]
 [2 0 1]]


Convert a vector of ints into a matrix binary representation

In [38]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Given a two dimensional array, how to extract unique rows?

In [39]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [41]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.15740964, 0.17534446, 0.00677939, 0.07430216, 0.09622237,
        0.05382494, 0.1372105 , 0.09573936, 0.00380341, 0.03425218],
       [0.21471016, 0.23917365, 0.00924724, 0.10134975, 0.1312494 ,
        0.07341839, 0.18715809, 0.13059057, 0.00518793, 0.04672072],
       [0.66997638, 0.74631164, 0.02885487, 0.3162493 , 0.40954744,
        0.22909296, 0.58400358, 0.40749164, 0.01618828, 0.1457862 ],
       [0.30482959, 0.33956103, 0.01312855, 0.14388887, 0.18633818,
        0.10423399, 0.26571321, 0.18540282, 0.00736544, 0.06633062],
       [0.07543997, 0.08403539, 0.00324908, 0.03560997, 0.04611542,
        0.02579608, 0.06575935, 0.04588394, 0.00182282, 0.01641566],
       [0.53058515, 0.59103855, 0.0228515 , 0.25045238, 0.32433948,
        0.18142926, 0.46249932, 0.32271139, 0.01282025, 0.1154548 ],
       [0.7172972 , 0.79902406, 0.0308929 , 0.33858617, 0.43847402,
        0.24527393, 0.62525208, 0.436273  , 0.01733167, 0.15608316],
       [0.60698887, 0.67614751, 0.0261420

Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [43]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [44]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [45]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.36860158  0.02551017]
