In [1]:
import numpy as np
np.__version__

'2.5.0'

In [2]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Outer Loop (for i in [2, 4, 6]): Iterates through three distinct values of i: 2, 4, and 6.

The List Comprehension: Generates a local Python range(i, i + 3) object for each iteration. Because standard Python range stops right before the upper limit, each range spans exactly 3 steps:
When i = 2: range(2, 5) → [2, 3, 4]
When i = 4: range(4, 7) → [4, 5, 6]
When i = 6: range(6, 9) → [6, 7, 8]

In [3]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.10491333, 0.24674629, 0.23179108],
       [0.75548186, 0.86734465, 0.46835259],
       [0.04904723, 0.13625896, 0.85570098]])

In [9]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.30454595, -1.12410757,  0.26181808],
       [-0.20897329,  0.97700901, -0.25907217],
       [ 1.07246755,  0.7963458 ,  0.96012555]])

In [10]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 1, 8],
       [9, 4, 2],
       [3, 5, 1]])

In [11]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [13]:
#NumPy Standard Data Types
np.zeros(10, dtype='int16')
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)